### ISSUE TITLE
About dataset and train json files

### ISSUE THREAD

**Issue by myknowntime** [lucasxlu/FGVC#1]
Your work is very charming and I am very interested in it. But I found it does not include dataset and train json file. Can you share the data and json file with me? Tanks a lot!

**Comment by lucasxlu** [comment]
> Your work is very charming and I am very interested in it. But I found it does not include dataset and train json file. Can you share the data and json file with me? Tanks a lot!

Hi, it's a workshop hold in CVPR'18. The dataset and detailed description can be found [here](https://sites.google.com/view/fgvc5/competitions/fgvcx/flowers).
